import type { FastifyInstance } from "fastify";
import adminSettingsRoutes from "./admin-settings.routes.js";
import activityRoutes from "./activity.routes.js";
import agreementsRoutes from "./agreements.routes.js";
import authRoutes from "./auth.routes.js";
import billingWebhooksRoutes from "./billing-webhooks.routes.js";
import billingRoutes from "./billing.routes.js";
import connectorsRoutes from "./connectors.routes.js";
import contractorsRoutes from "./contractors.routes.js";
import dashboardRoutes from "./dashboard.routes.js";
import documentsRoutes from "./documents.routes.js";
import duplicatesRoutes from "./duplicates.routes.js";
import filesDownloadRoutes from "./files-download.routes.js";
import healthRoutes from "./health.routes.js";
import ingestionRoutes from "./ingestion.routes.js";
import invoiceFilesRoutes from "./invoice-files.routes.js";
import invoicesRoutes from "./invoices.routes.js";
import integrationsRoutes from "./integrations.routes.js";
import workflowsRoutes from "./workflows.routes.js";
import ksefRoutes from "./ksef.routes.js";
import platformAdminRoutes from "./platform-admin.routes.js";
import reportsRoutes from "./reports.routes.js";
import supportRoutes from "./support.routes.js";
import tenantRoutes from "./tenant.routes.js";
import zenboxRoutes from "./zenbox.routes.js";

export async function registerApiRoutes(app: FastifyInstance): Promise<void> {
  await app.register(healthRoutes);
  await app.register(authRoutes);
  await app.register(billingWebhooksRoutes);
  await app.register(billingRoutes);
  await app.register(tenantRoutes);
  await app.register(activityRoutes);
  await app.register(agreementsRoutes);
  await app.register(dashboardRoutes);
  await app.register(reportsRoutes);
  await app.register(supportRoutes);
  await app.register(documentsRoutes);
  await app.register(duplicatesRoutes);
  await app.register(ingestionRoutes);
  await app.register(connectorsRoutes);
  await app.register(ksefRoutes);
  await app.register(platformAdminRoutes);
  await app.register(zenboxRoutes);
  await app.register(workflowsRoutes);
  await app.register(adminSettingsRoutes);
  await app.register(contractorsRoutes);
  await app.register(invoicesRoutes);
  await app.register(invoiceFilesRoutes);
  await app.register(filesDownloadRoutes);
  await app.register(integrationsRoutes);
}
